name: Frends.AzureEventHub.Receive Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.AzureEventHub.Receive/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.AzureEventHub.Receive
      env_var_name_1: EVENT_HUB_CONNECTION_STRING
      env_var_name_2: HIQ_AZUREBLOBSTORAGE_CONNSTRING
      env_var_name_3: HIQ_AZUREBLOBSTORAGE_APPID
      env_var_name_4: HIQ_AZUREBLOBSTORAGE_TENANTID
      env_var_name_5: HIQ_AZUREBLOBSTORAGE_CLIENTSECRET
      env_var_name_6: HIQ_AZUREBLOBSTORAGE_TESTSORAGE01ACCESSKEY
      env_var_name_7: HIQ_AZUREEVENTHUB_FULLYQUALIFIEDNAMESPACE
      env_var_name_8: HIQ_AZUREEVENTHUB_KEY
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.EVENT_HUB_CONNECTION_STRING }}
      env_var_value_2: ${{ secrets.HiQ_AzureBlobStorage_ConnString }}
      env_var_value_3: ${{ secrets.HiQ_AzureBlobStorage_AppID }}
      env_var_value_4: ${{ secrets.HiQ_AzureBlobStorage_TenantID }}
      env_var_value_5: ${{ secrets.HiQ_AzureBlobStorage_ClientSecret }}
      env_var_value_6: ${{ secrets.HiQ_AzureBlobStorage_testsorage01AccessKey }}
      env_var_value_7: ${{ secrets.HIQ_AzureEventHub_FullyQualifiedNamespace }}
      env_var_value_8: ${{ secrets.HIQ_AzureEventHub_Key }}