name: UpdateCheckpoint_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.AzureEventHub.UpdateCheckpoint/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.AzureEventHub.UpdateCheckpoint
      env_var_name_1: FRENDS__AZURE_EVENT_HUB__CONNECTION_STRING
      env_var_name_2: FRENDS__AZURE_BLOB_STORAGE__APP_ID
      env_var_name_3: FRENDS__AZURE_BLOB_STORAGE__CLIENT_SECRET
      env_var_name_4: FRENDS__AZURE_BLOB_STORAGE__CONNECTION_STRING
      env_var_name_5: FRENDS__AZURE_BLOB_STORAGE__TENANT_ID
      env_var_name_6: FRENDS__AZURE_BLOB_STORAGE__ACCESS_KEY
      env_var_name_7: FRENDS__AZURE_EVENT_HUB__FULLY_QUALIFIED_NAMESPACE
      dotnet_version: 8.0.x
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS__AZURE_EVENT_HUB__CONNECTION_STRING }}
      env_var_value_2: ${{ secrets.FRENDS__AZURE_BLOB_STORAGE__APP_ID }}
      env_var_value_3: ${{ secrets.FRENDS__AZURE_BLOB_STORAGE__CLIENT_SECRET }}
      env_var_value_4: ${{ secrets.FRENDS__AZURE_BLOB_STORAGE__CONNECTION_STRING }}
      env_var_value_5: ${{ secrets.FRENDS__AZURE_BLOB_STORAGE__TENANT_ID }}
      env_var_value_6: ${{ secrets.FRENDS__AZURE_BLOB_STORAGE__ACCESS_KEY }}
      env_var_value_7: ${{ secrets.FRENDS__AZURE_EVENT_HUB__FULLY_QUALIFIED_NAMESPACE }}
